# 基于microsoft/dotnet:latest构建Docker Image
FROM microsoft/dotnet:latest

 
# 设置工作路径
WORKDIR /app
 
# 将当前文件夹下的所有文件全部复制到工作目录
COPY . .　
 
# 向外界暴露5000端口
EXPOSE 6000
#字符集设置
ENV LANG C.UTF-8
#设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 执行dotnet DockerWebAPI.dll命令
CMD ["dotnet", "WebApi.dll"]


